incorporated review comments

diff --git a/release-pipeline.yml b/release-pipeline.yml
--- a/release-pipeline.yml
+++ b/release-pipeline.yml
@@ -78,7 +78,6 @@ stages:
                 
                 # Trigger the workflow
                 response=$(curl -w "%{http_code}" -X POST -H "Authorization: Bearer $(GITHUB_TOKEN)" -H "Accept: application/vnd.github.v3+json" $GITHUB_API_URL -d "$PAYLOAD")
-                #response=$(curl -X POST -H "Accept: application/vnd.github.v3+json" -H "authorization: Bearer $GIT_TOKEN" -d \'{"ref":"$GITHUB_REF"}\' "$GITHUB_API_URL")
                 echo "response: $response"
 
                 if [ $response -eq 204 ]; then
@@ -87,6 +86,66 @@ stages:
                   echo "Failed to trigger the workflow $response"
                   exit 1
                 fi
+
+
+                # GitHub API URL to list workflows
+                WORKFLOWS_URL="https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/actions/workflows"
+
+                # Retrieve workflows
+                response=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $(GITHUB_TOKEN)" "$WORKFLOWS_URL")
+
+                # Extract the workflow ID for the specified workflow name
+                workflow_id=$(echo $response | jq -r --arg workflow_name "$GITHUB_WORKFLOW_NAME" '.workflows[] | select(.name == $workflow_name) | .id')
+
+                if [ -z "$workflow_id" ]; then
+                  echo "Workflow not found"
+                  exit 1
+                else
+                  echo "Workflow ID: $workflow_id"
+                fi
+
+                # Interval between polls (in seconds)
+                POLL_INTERVAL=15
+
+                # GitHub API URL to list workflow runs
+                WORKFLOW_RUNS_URL="https://api.github.com/repos/$GITHUB_OWNER/$GITHUB_REPO/actions/workflows/$workflow_id/runs"
+
+                # Function to check the status of the latest workflow run
+                check_status() {
+                  runs_response=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $(GITHUB_TOKEN)" "$WORKFLOW_RUNS_URL")
+
+                  latest_run_status=$(echo $runs_response | jq -r '.workflow_runs[0].status')
+                  latest_run_conclusion=$(echo $runs_response | jq -r '.workflow_runs[0].conclusion')
+                  latest_run_id=$(echo $runs_response | jq -r '.workflow_runs[0].id')
+
+                  if [ -z "$latest_run_id" ]; then
+                    echo "No runs found for the workflow"
+                    exit 1
+                  else
+                    echo "Latest Run ID: $latest_run_id"
+                    echo "Latest Run Status: $latest_run_status"
+                    echo "Latest Run Conclusion: $latest_run_conclusion"
+                  fi
+
+                  if [ "$latest_run_status" == "completed" ]; then
+                    if [ "$latest_run_conclusion" == "success" ]; then
+                      echo "Workflow run succeeded."
+                      exit 0
+                    else
+                      echo "Workflow run failed or was cancelled."
+                      exit 1
+                    fi
+                  fi
+                }
+
+                # Poll the workflow status until it completes
+                while true; do
+                  check_status
+                  echo "Workflow run is still in progress. Checking again in $POLL_INTERVAL seconds..."
+                  sleep $POLL_INTERVAL
+                done
+
+
       # - job: Set_1
       #   timeoutInMinutes: 120
       #   strategy:
